image: docker:latest
services:
  - docker:dind

stages:
  - build
  - package
  - deploy

build:
  image: gradle:6.7.1-jre15
  stage: build
  script:
    - gradle build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day

package:
  stage: package
  script:
    - docker build -t $CI_REGISTRY/troojer/ms-notification .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/troojer/ms-notification

deploy:
  image:
    name: alpine:latest
  stage: deploy
  before_script:
    - apk update
    - apk add curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv kubectl /bin/kubectl
  script:
    - kubectl scale --replicas=0 deployment ms-notification --kubeconfig config
    - sleep 15
    - kubectl scale --replicas=1 deployment ms-notification --kubeconfig config
