image: docker:latest
services:
  - docker:dind

variables:
  PROJECT_NAME: "ms-notification"

stages:
  - build
  - package
  - deploy

build:
  image: gradle:6.7.1-jre15
  stage: build
  script:
    - gradle build

  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day

package:
  stage: package
  script:
    - ls -alh
    - pwd
    - ls -alh build/libs/
    - docker build -t $CI_REGISTRY/troojer/$PROJECT_NAME .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/troojer/$PROJECT_NAME

deploy:
  image:
    name: alpine:latest
  stage: deploy
  before_script:
    - apk update
    - apk add curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv kubectl /bin/kubectl
  script:
    - kubectl scale --replicas=0 deployment $PROJECT_NAME -n app --kubeconfig $KUBECONFIG
    - sleep 15
    - kubectl scale --replicas=1 deployment $PROJECT_NAME -n app --kubeconfig $KUBECONFIG
