spring:
  rabbitmq:
    host: ${RABBITMQ_URL}
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_USER_PASSWORD}
  datasource:
    url: jdbc:postgresql://${DATABASE_URL}/ms_notification
    username: ${MS_NOTIFICATION_USER}
    password: ${MS_NOTIFICATION_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
server:
  port: 8088
client:
  localization:
    url: http://ms-localization:8080/
logging:
  my-level: INFO
firebase-push-notification:
  api-url: https://fcm.googleapis.com/fcm/send
  server-key: ${FIREBASE-SERVER-KEY}