spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_notification
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
client:
  localization:
    url: http://localhost:8084/