spring:
  rabbitmq:
    host: rabbitmq.rabbitmq.svc.cluster.local
    port: 5672
    username: admin
    password: P@ssw0rD
  datasource:
    url: jdbc:postgresql://postgres-postgresql.postgres.svc.cluster.local:5432/ms_notification
    username: postgres
    password: P@ssw0rD
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
server:
  port: 8088
client:
  localization:
    url: http://ms-localization:8080/
