spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  datasource:
    url: jdbc:postgresql://192.168.1.100:30058/ms_notification
    username: postgres
    password: P@ssw0rD
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
client:
  localization:
    url: http://localhost:8084/
  message:
    url: http://localhost:8092/private/messages/